/**
 * All user-facing strings live here.
 *
 * The operators using this product are Mexican, so the interface is es-MX while
 * code identifiers stay English. Centralising copy in one file keeps that an
 * assumption we can reverse cheaply.
 */

export const copy = {
  app: {
    name: 'FIRMA23 Ops',
    sliceBanner: 'Rebanada 1 · núcleo financiero',
    sliceNote:
      'Datos sintéticos. Sin Supabase, sin despliegue. Esta pantalla existe para revisar el contrato de dinero y el Riel de Ingresos.',
    syntheticAuthority:
      'Modo de demostración: estos datos son sintéticos y no representan contratos ni dinero operativo.',
    configuredSyntheticAuthority:
      'Sesión real, datos no canónicos: estas pantallas todavía usan registros sintéticos; ningún monto mostrado proviene del ledger de Supabase.',
    configuredCanonicalAuthority:
      'Sesión real: estas rutas leen registros canónicos de Supabase. Las proyecciones no son dinero aprobado ni pagable.',
  },
  money: {
    projected: 'Proyección',
    projectedLong: 'Proyección no aprobada',
    approved: 'Aprobado',
    paid: 'Pagado',
    unpaid: 'Por pagar',
    base: 'Base distribuible',
    cashReceived: 'Efectivo recibido',
    excludedFromBase: 'Fuera de la base distribuible',
    notEarnedYet: 'Aún no es dinero ganado ni por pagar',
    approvedBy: 'Aprobado por',
    rulePrefix: 'Regla',
    unassigned: 'Sin asignar',
    ofSegment: 'del segmento',
  },
  rail: {
    label: 'Riel de Ingresos',
    projectionAria: 'Riel de ingresos proyectado, no aprobado',
    settlementAria: 'Riel de ingresos liquidado y aprobado',
    correctionAria: 'Riel de ingresos pendiente de corrección, sin proyección vigente',
    correctionRequired: 'Corrección requerida',
    correctionDetail:
      'La liquidación fue revertida. Crea un borrador de reemplazo antes de proyectar.',
    incompleteAssignment: 'Asignación incompleta',
  },
  states: {
    loading: 'Cargando…',
    empty: 'Sin registros todavía',
    error: 'No se pudo cargar la información',
    permissionDenied: 'Necesitas permisos de fundador para ver este detalle',
    retry: 'Reintentar',
    notFound: 'No encontramos eso',
    notFoundDetail: 'El registro no existe o cambió de lugar.',
  },
  nav: {
    home: 'Home',
    opportunities: 'Contracts',
    network: 'Network',
    leaderboard: 'Performance',
    admin: 'Admin',
    projects: 'Proyectos',
    finance: 'Finanzas',
    workspace: 'Operación',
    control: 'Control',
    collapse: 'Contraer menú lateral',
    expand: 'Expandir menú lateral',
    session: 'Sesión',
    soon: 'Pronto',
    primary: 'Navegación principal',
    mobile: 'Navegación inferior',
    breadcrumb: 'Ruta actual',
    hide: 'Ocultar menú lateral',
    show: 'Mostrar menú lateral',
    allProjects: 'Todos los proyectos',
    expandGroup: 'Desplegar',
    collapseGroup: 'Plegar',
    orgSubtitle: 'Red privada',
    switchViewer: 'Cambiar vista de prototipo',
    skipToContent: 'Saltar al contenido',
    pendingApprovals: 'liquidaciones por aprobar',
  },
  search: {
    open: 'Buscar',
    shortcut: '⌘K',
    placeholder: 'Busca una sección, un proyecto o una acción…',
    empty: 'Sin resultados',
    hint: 'Escribe para navegar',
    close: 'Cerrar búsqueda',
    dismiss: 'ESC',
    sections: 'Secciones',
    projects: 'Proyectos',
  },
  home: {
    greeting: 'Tu operación',
    snapshot: 'Panel personal',
    approvedLedger: 'Dinero aprobado',
    approved: 'Aprobado',
    paid: 'Cobrado',
    pendingPayout: 'Por cobrar',
    actionQueue: 'Cola operativa',
    workInFocus: 'Trabajo en foco',
    nextMove: 'Siguiente movimiento',
    projectField: 'Campo de proyecto',
    privateLedger: 'Registro privado',
    openOpportunity: 'Abrir oportunidad',
    browseOpportunities: 'Explorar oportunidades',
    browseProjects: 'Explorar proyectos',
    projectedAside: 'Proyección en curso',
    primaryAction: 'Subir evidencia',
    primaryActionUnavailable: 'La carga de evidencia todavía no tiene una ruta autorizada.',
    assignments: 'Mis asignaciones',
    nextActions: 'Siguientes pasos',
    actionEvidence: 'Sube evidencia',
    actionSettle: 'Revisa liquidación',
    noAssignments: 'Todavía no tienes trabajo asignado',
    noAssignmentsDetail: 'Cuando un fundador te asigne una oportunidad, aparecerá aquí.',
    noActions: 'Nada pendiente por ahora',
    commandCenter: 'Command center',
    workstream: 'Actividad verificable',
    liveNow: 'Ahora',
    unitActive: 'oportunidad activa en tu operación',
    unitsActive: 'oportunidades activas en tu operación',
    commandStrip: {
      identityCode: 'FIRMA23 / MIEMBRO',
      activeOperation: 'operación activa',
      activeOperations: 'operaciones activas',
      timeZone: 'CST',
      instrumentLabel: 'Posición personal',
      historyLabel: 'Historial verificable',
      currentValue: 'Valor actual',
      eventDetail: 'Evento de origen',
      correction: 'Corrección',
      recovery: 'Recuperación pendiente',
      noHistory: 'Aún no hay historial verificable.',
      noPeriodEvents: 'Sin movimientos verificables en este periodo.',
      historyUnavailable: 'Este valor aún no tiene eventos fechados para construir una línea.',
      periodLabel: 'Periodo del historial',
      metricLabel: 'Métrica personal',
      chartLabel: 'Evolución por eventos verificables',
      chartModeLabel: 'Vista del historial',
      balanceMode: 'Ver saldo por evento',
      eventsMode: 'Ver movimientos individuales',
      periodChange: 'Movimiento',
      periodPeak: 'Máximo',
      periodLow: 'Mínimo',
      periodAverage: 'Promedio',
      periods: {
        days30: '30D',
        months3: '3M',
        months6: '6M',
        year: 'AÑO',
        all: 'TODO',
      },
      metrics: {
        approved: {
          label: 'Ganado confirmado',
          shortLabel: 'Ganado',
          definition: 'Aprobado mediante una liquidación verificada.',
        },
        paid: {
          label: 'Cobrado',
          shortLabel: 'Cobrado',
          definition: 'Dinero aprobado que ya fue pagado.',
        },
        approvedUnpaid: {
          label: 'Por cobrar',
          shortLabel: 'Por cobrar',
          definition: 'Dinero aprobado que sigue pendiente de pago.',
        },
        projected: {
          label: 'Proyección',
          shortLabel: 'Proyección',
          definition: 'Ingreso potencial. No está ganado ni es pagable.',
        },
        closed: {
          label: 'Cierres',
          shortLabel: 'Cierres',
          definition: 'Oportunidades cerradas mediante eventos verificados.',
        },
      },
      sources: {
        settlementApproved: 'Liquidación aprobada',
        settlementCorrected: 'Corrección de liquidación',
        payoutRecorded: 'Pago registrado',
        payoutCorrected: 'Corrección de pago',
        closeVerified: 'Cierre verificado',
        closeCorrected: 'Corrección de cierre',
      },
    },
  },
  viewer: {
    label: 'Vista de prototipo',
    founder: 'Fundador',
    member: 'Operador',
    warning: 'Selector de prototipo. No otorga permisos: la autorización real llega con RLS en M2.',
  },
  auth: {
    title: 'Acceso privado',
    subtitle: 'Red operativa por invitación. Escribe tu correo y te enviamos un enlace de acceso.',
    emailLabel: 'Correo',
    emailPlaceholder: 'tu@correo.com',
    submit: 'Enviar enlace de acceso',
    sending: 'Enviando…',
    sentTitle: 'Revisa tu correo',
    sentDetail: 'Te enviamos un enlace de acceso a tu correo. Ábrelo desde este mismo dispositivo.',
    genericError: 'No pudimos enviar el enlace. Intenta de nuevo en un momento.',
    notInvitedTitle: 'Esta cuenta no tiene invitación',
    notInvitedDetail:
      'Iniciaste sesión correctamente, pero tu correo no tiene una invitación activa a esta red. Pide a un fundador que te invite.',
    inviteExpiredTitle: 'La invitación expiró',
    inviteExpiredDetail: 'Tu invitación venció. Pide a un fundador que te envíe una nueva.',
    revokedTitle: 'Tu acceso fue revocado',
    revokedDetail:
      'Un fundador revocó tu membresía. Si crees que es un error, contacta a un fundador.',
    invalidSessionTitle: 'Tu sesión ya no es válida',
    invalidSessionDetail: 'Necesitamos que inicies sesión de nuevo.',
    backendUnavailableTitle: 'El servicio no está disponible',
    backendUnavailableDetail: 'No pudimos conectar con el backend. Intenta de nuevo en un momento.',
    signOut: 'Cerrar sesión',
    signedInAs: 'Sesión activa',
    backToLogin: 'Volver a iniciar sesión',
  },
  board: {
    title: 'Contracts',
    subtitle: 'Trabajo creado por fundadores, con su riel de ingresos.',
    filterProject: 'Proyecto',
    filterStatus: 'Estado',
    filterAll: 'Todas',
    noMatches: 'Ninguna oportunidad coincide con el filtro',
  },
  projects: {
    title: 'Proyectos',
    subtitle: 'Cada proyecto define sus propios servicios y sus propias reglas de reparto.',
    services: 'Servicios',
    rules: 'Reglas de reparto',
    activeRule: 'Regla activa',
    noRule: 'Sin regla de reparto todavía',
    noServices: 'Sin servicios definidos todavía',
    noOpportunities: 'Sin contratos todavía',
    settledApproved: 'Liquidado y aprobado',
    opportunitiesCount: 'Contracts',
    statusLabels: { draft: 'Borrador', active: 'Activo', closed: 'Cerrado' },
    versionPrefix: 'v',
    milestones: 'hitos',
    filterProject: 'Proyecto',
    filterStatus: 'Estado',
  },
  detail: {
    milestones: 'Hitos',
    evidence: 'Evidencia',
    assignments: 'Equipo asignado',
    ledger: 'Movimientos de efectivo',
    inBase: 'En la base',
    outOfBase: 'Fuera de la base',
    weights: 'Pesos',
    weightsBalanced: 'Pesos completos',
    weightsUnbalanced: 'Pesos incompletos',
    milestoneStatus: {
      pending: 'Pendiente',
      in_progress: 'En curso',
      done: 'Hecho',
      blocked: 'Bloqueado',
    },
    noEvidence: 'Sin evidencia todavía',
    dueAt: 'Vence',
    completedAt: 'Completado',
    crew: {
      manage: 'Gestionar equipo',
      title: 'Gestión de equipo',
      subtitle: 'Reemplaza el equipo asignado. Los pesos deben sumar 100%.',
      memberLabel: 'Miembro',
      roleLabel: 'Rol en el contrato',
      weightLabel: 'Peso (%)',
      addMember: 'Agregar integrante',
      removeMember: 'Quitar integrante',
      total: 'Total',
      totalBalanced: 'Pesos completos al 100%',
      totalUnbalanced: 'Los pesos deben sumar exactamente 100%',
      cancel: 'Cancelar',
      submit: 'Guardar equipo',
      submitting: 'Guardando equipo…',
      saved: 'Equipo actualizado.',
      error: 'No pudimos actualizar el equipo.',
      unavailable: 'Gestionar el equipo requiere un backend de Supabase configurado.',
      required: 'Agrega al menos un integrante, un rol para cada uno y pesos que sumen 100%.',
      noMembers: 'No hay integrantes activos disponibles para asignar.',
      history: 'Historial del equipo',
      historyEmpty: 'Aún no hay cambios de equipo registrados.',
      previousCrew: 'Antes',
      replacementCrew: 'Después',
    },
  },
  network: {
    title: 'Network',
    subtitle: 'Operadores, habilidades verificadas y trabajo comprobable.',
    availability: {
      open: 'Disponible',
      limited: 'Capacidad limitada',
      unavailable: 'Sin capacidad',
    },
    level: { learning: 'Aprendiendo', working: 'Trabajando', strong: 'Sólido', lead: 'Referente' },
    verified: 'Verificado',
    selfReported: 'Autodeclarado',
    nextCapability: 'Construyendo',
    portfolio: 'Portafolio',
    recentWork: 'Trabajo reciente',
    stats: 'Desempeño',
    skills: 'Habilidades',
    closed: 'Cerradas',
    delivered: 'Entregas',
    onTime: 'A tiempo',
    acceptance: 'Aceptación directa',
    noRate: 'Sin datos',
    verifiedOutcomes: 'Resultados verificados',
    joined: 'Desde',
    filterSkill: 'Habilidad',
    filterAvailability: 'Disponibilidad',
    filterAll: 'Todas',
    noMembers: 'Todavía no hay miembros',
    activeWork: 'Trabajo activo',
    roster: 'Roster operativo',
    directoryTitle: 'Network',
    carouselLabel: 'Miembros de Network',
    previousMember: 'Ver miembro anterior',
    nextMember: 'Ver miembro siguiente',
    showMember: 'Mostrar miembro',
  },
  leaderboard: {
    title: 'Performance',
    subtitle: 'Ordenado únicamente por dinero aprobado. Las proyecciones no rankean.',
    rank: 'Lugar',
    operator: 'Operador',
    approved: 'Aprobado',
    paid: 'Pagado',
    projected: 'Proyectado',
    closed: 'Cerradas',
    delivered: 'Entregas',
    onTime: 'A tiempo',
    provenance: 'Ver origen',
    provenanceTitle: 'Origen del dinero aprobado',
    provenanceSubtitle: 'Cada línea proviene de una liquidación aprobada por un fundador.',
    noProvenance: 'Todavía no hay liquidaciones aprobadas para este operador',
    projectedNote: 'La columna proyectada existe como contexto. No entra en el orden.',
  },
  finance: {
    title: 'Finanzas',
    subtitle: 'Detalle completo de efectivo, base distribuible y liquidaciones.',
    cashReceived: 'Efectivo recibido',
    approvedBase: 'Base aprobada',
    projectedBase: 'Base proyectada',
    paidOut: 'Pagado',
    owed: 'Por pagar',
    recovery: 'Por recuperar o reasignar',
    house: 'Casa',
    pendingApprovals: 'Liquidaciones por aprobar',
    ledger: 'Movimientos',
    review: 'Revisar liquidación',
    writeBlockedReason:
      'Esta operación requiere un backend de Supabase configurado. Este entorno no tiene uno conectado todavía.',
  },
  settle: {
    title: 'Aprobación de liquidación',
    subtitle: 'Vista previa. En M1 no existe ninguna ruta de escritura.',
    approve: 'Aprobar liquidación',
    blockedInM1: 'La aprobación se habilita en M2, con RLS y registro de auditoría en Postgres.',
    checks: 'Verificaciones',
    checkWeights: 'Pesos completos',
    checkMilestones: 'Hitos pendientes',
    checkBase: 'Base distribuible confirmada',
    alreadyApproved: 'Esta oportunidad ya tiene una liquidación aprobada',
  },
  admin: {
    title: 'Admin',
    subtitle: 'Vista de fundador sobre proyectos, cartera y aprobaciones.',
    portfolio: 'Cartera',
    attention: 'Requiere atención',
    nothingPending: 'Nada pendiente',
    members: {
      manage: 'Administrar integrantes', pageTitle: 'Integrantes',
      pageSubtitle: 'Crea accesos pendientes para integrantes de esta organización.',
      title: 'Agregar integrante', subtitle: 'Crea la invitación local y el acceso pendiente de la persona.',
      nameLabel: 'Nombre', emailLabel: 'Correo de invitación', create: 'Crear invitación', creating: 'Creando invitación…',
      created: 'Invitación creada. El acceso queda pendiente de activación.', deliveryNote: 'Crear una invitación no envía un correo automáticamente.',
      roster: 'Invitaciones y accesos', empty: 'No hay invitaciones todavía.',
      status: { invited: 'Pendiente de activación', active: 'Activo', revoked: 'Revocado' },
      backendUnavailable: 'Crear integrantes requiere un backend de Supabase configurado.', error: 'No pudimos crear la invitación.',
    },
    intake: {
      ctaUpload: 'Subir propuesta',
      ctaManual: 'Crear manualmente',
      ctaManualHint: 'Editor de respaldo. El flujo principal siempre empieza con un documento.',
      dropTitle: 'Arrastra tu documento aquí',
      dropHint: 'Propuesta, informe ejecutivo, deck, cotización o alcance de trabajo (SOW).',
      chooseFile: 'Elegir archivo',
      selectedFile: 'Archivo seleccionado',
      changeFile: 'Elegir otro documento',
      process: 'Procesar documento',
      processing: 'Analizando documento…',
      processingError: 'No pudimos procesar el documento. Reintenta cuando el servicio responda.',
      readyAnnouncement: 'El borrador está listo para revisión.',
      syntheticNotice:
        'Vista previa sintética: este entorno no analiza el contenido real del archivo ni llama a ningún proveedor de IA. Usa datos de referencia de SETY 2026 para mostrar cómo se vería el resultado.',
      draftTitle: 'Borrador extraído',
      matchedProject: 'Coincide con el contrato',
      noMatchedProject: 'Sin contrato existente que coincida',
      fields: 'Campos extraídos',
      services: 'Servicios detectados',
      milestones: 'Hitos sugeridos',
      assignments: 'Asignaciones sugeridas',
      shareOfBaseSuffix: 'de la base distribuible',
      allocation: 'Proyección de reparto',
      review: 'Por revisar antes de confirmar',
      missing: 'Falta',
      ambiguous: 'Ambiguo',
      confidence: { high: 'Confianza alta', medium: 'Confianza media', low: 'Confianza baja' },
      evidence: 'Evidencia',
      confirm: 'Confirmar y crear contrato',
      confirmMatched: 'Confirmar contrato existente',
      confirmHint: 'Nada se crea hasta que confirmes.',
      confirmBlockedReason:
        'La confirmación requiere un backend de Supabase configurado. Este entorno no tiene uno conectado todavía.',
      confirmed: 'Contrato confirmado.',
      discard: 'Descartar borrador',
      confirmDiscard: 'Confirmar descarte',
      cancelDiscard: 'Conservar borrador',
      discardWarning: 'Confirma el descarte. Esta acción no crea ningún contrato.',
      discarded: 'Borrador descartado. No se creó ningún contrato.',
      confirmRejected: 'No pudimos confirmar el contrato. El borrador sigue disponible.',
      confirmPending: 'Confirmando contrato…',
      discardUnavailable: 'No se puede descartar en este entorno. El borrador sigue disponible.',
      discardError: 'No pudimos descartar el borrador. Consérvalo o reintenta.',
      discardPending: 'Descartando borrador…',
      retryDiscard: 'Reintentar descarte',
      retry: 'Reintentar',
      manualCta: 'Crear contrato manual',
      manualTitle: 'Contrato manual',
      manualSubtitle: 'Crea un contrato real con equipo asignado y una bolsa proyectada no contable.',
      manualSponsorLabel: 'Cliente',
      manualProgramLabel: 'Contrato',
      manualServiceScopeLabel: 'Servicio y alcance',
      manualProjectedBaseLabel: 'Bolsa proyectada para distribución (MXN)',
      manualFirma23ShareLabel: 'Participación FIRMA23 (%)',
      manualMemberLabel: 'Miembro',
      manualRoleLabel: 'Rol en el contrato',
      manualWeightLabel: 'Peso del equipo (%)',
      manualAddMember: 'Agregar integrante',
      manualRemoveMember: 'Quitar integrante',
      manualReview: 'Resumen de revisión',
      manualRequired: 'Completa cliente, contrato, alcance, monto positivo y pesos del equipo al 100%.',
      manualCancel: 'Cancelar',
      manualSubmit: 'Crear contrato',
      manualSubmitting: 'Creando contrato…',
      manualCreated: 'Contrato creado.',
      manualError: 'No pudimos crear el contrato.',
      fileTooLarge: 'El archivo supera los 20 MB. Sube un documento más ligero.',
      fileTypeUnsupported: 'Ese tipo de archivo no es un formato de propuesta reconocido.',
      fileTypeHint: 'PDF, Word, PowerPoint o texto plano.',
      stepper: {
        ariaLabel: 'Progreso de la propuesta',
        document: 'Documento',
        extraction: 'Extracción',
        review: 'Revisión',
        confirmation: 'Confirmación',
      },
      stepStatus: {
        complete: 'completo',
        current: 'actual',
        upcoming: 'pendiente',
      },
    },
  },
  opportunity: {
    statusLabels: {
      draft: 'Borrador',
      assigned: 'Asignada',
      in_delivery: 'En producción',
      delivered: 'Entregada',
      settled_approved: 'Liquidada',
      paid: 'Pagada',
      cancelled: 'Cancelada',
    },
  },
} as const;
