/**
 * All user-facing strings live here.
 *
 * The operators using this product are Mexican, so the interface is es-MX while
 * code identifiers stay English. Centralising copy in one file keeps that an
 * assumption we can reverse cheaply.
 */

export const copy = {
  app: {
    name: 'FIRMA23 Ops',
    sliceBanner: 'Rebanada 1 · núcleo financiero',
    sliceNote:
      'Datos sintéticos. Sin Supabase, sin despliegue. Esta pantalla existe para revisar el contrato de dinero y el Riel de Ingresos.',
  },
  money: {
    projected: 'Proyección',
    projectedLong: 'Proyección no aprobada',
    approved: 'Aprobado',
    paid: 'Pagado',
    unpaid: 'Por pagar',
    base: 'Base distribuible',
    cashReceived: 'Efectivo recibido',
    excludedFromBase: 'Fuera de la base distribuible',
    notEarnedYet: 'Aún no es dinero ganado ni por pagar',
    approvedBy: 'Aprobado por',
    rulePrefix: 'Regla',
    unassigned: 'Sin asignar',
    ofSegment: 'del segmento',
  },
  rail: {
    label: 'Riel de Ingresos',
    projectionAria: 'Riel de ingresos proyectado, no aprobado',
    settlementAria: 'Riel de ingresos liquidado y aprobado',
    incompleteAssignment: 'Asignación incompleta',
  },
  states: {
    loading: 'Cargando…',
    empty: 'Sin registros todavía',
    error: 'No se pudo cargar la información',
    permissionDenied: 'Necesitas permisos de fundador para ver este detalle',
    retry: 'Reintentar',
    notFound: 'No encontramos eso',
    notFoundDetail: 'El registro no existe o cambió de lugar.',
  },
  nav: {
    home: 'Inicio',
    opportunities: 'Oportunidades',
    network: 'Red',
    leaderboard: 'Ranking',
    admin: 'Admin',
    soon: 'Pronto',
    primary: 'Navegación principal',
    mobile: 'Navegación inferior',
  },
  home: {
    greeting: 'Tu operación',
    approved: 'Aprobado',
    pendingPayout: 'Por cobrar',
    activeWork: 'Trabajo activo',
    projectedAside: 'Proyección en curso',
    primaryAction: 'Subir evidencia',
    assignments: 'Mis asignaciones',
    nextActions: 'Siguientes pasos',
    actionEvidence: 'Sube evidencia',
    actionSettle: 'Revisa liquidación',
    noAssignments: 'Todavía no tienes trabajo asignado',
    noAssignmentsDetail: 'Cuando un fundador te asigne una oportunidad, aparecerá aquí.',
    noActions: 'Nada pendiente por ahora',
    unitsActive: 'oportunidades',
  },
  viewer: {
    label: 'Vista de prototipo',
    founder: 'Fundador',
    member: 'Operador',
    warning: 'Selector de prototipo. No otorga permisos: la autorización real llega con RLS en M2.',
  },
  board: {
    title: 'Oportunidades',
    subtitle: 'Trabajo creado por fundadores, con su riel de ingresos.',
    filterProject: 'Proyecto',
    filterStatus: 'Estado',
    filterAll: 'Todas',
    noMatches: 'Ninguna oportunidad coincide con el filtro',
  },
  projects: {
    title: 'Proyectos',
    subtitle: 'Cada proyecto define sus propios servicios y sus propias reglas de reparto.',
    services: 'Servicios',
    rules: 'Reglas de reparto',
    activeRule: 'Regla activa',
    noRule: 'Sin regla de reparto todavía',
    noServices: 'Sin servicios definidos todavía',
    noOpportunities: 'Sin oportunidades todavía',
    settledApproved: 'Liquidado y aprobado',
    opportunitiesCount: 'Oportunidades',
    statusLabels: { draft: 'Borrador', active: 'Activo', closed: 'Cerrado' },
    versionPrefix: 'v',
    milestones: 'hitos',
  },
  detail: {
    milestones: 'Hitos',
    evidence: 'Evidencia',
    assignments: 'Equipo asignado',
    ledger: 'Movimientos de efectivo',
    inBase: 'En la base',
    outOfBase: 'Fuera de la base',
    weights: 'Pesos de producción',
    weightsBalanced: 'Pesos completos',
    weightsUnbalanced: 'Pesos incompletos',
    milestoneStatus: {
      pending: 'Pendiente',
      in_progress: 'En curso',
      done: 'Hecho',
      blocked: 'Bloqueado',
    },
    noEvidence: 'Sin evidencia todavía',
    dueAt: 'Vence',
    completedAt: 'Completado',
  },
  network: {
    title: 'Red',
    subtitle: 'Operadores, habilidades verificadas y trabajo comprobable.',
    availability: {
      open: 'Disponible',
      limited: 'Capacidad limitada',
      unavailable: 'Sin capacidad',
    },
    level: { learning: 'Aprendiendo', working: 'Trabajando', strong: 'Sólido', lead: 'Referente' },
    verified: 'Verificado',
    selfReported: 'Autodeclarado',
    nextCapability: 'Construyendo',
    portfolio: 'Portafolio',
    recentWork: 'Trabajo reciente',
    stats: 'Desempeño',
    closed: 'Cerradas',
    delivered: 'Entregas',
    onTime: 'A tiempo',
    acceptance: 'Aceptación directa',
    noRate: 'Sin datos',
    joined: 'Desde',
    filterSkill: 'Habilidad',
    filterAvailability: 'Disponibilidad',
    filterAll: 'Todas',
    noMembers: 'Ningún operador coincide con el filtro',
  },
  leaderboard: {
    title: 'Ranking',
    subtitle: 'Ordenado únicamente por dinero aprobado. Las proyecciones no rankean.',
    rank: 'Lugar',
    operator: 'Operador',
    approved: 'Aprobado',
    paid: 'Pagado',
    projected: 'Proyectado',
    closed: 'Cerradas',
    delivered: 'Entregas',
    onTime: 'A tiempo',
    provenance: 'Ver origen',
    provenanceTitle: 'Origen del dinero aprobado',
    provenanceSubtitle: 'Cada línea proviene de una liquidación aprobada por un fundador.',
    noProvenance: 'Todavía no hay liquidaciones aprobadas para este operador',
    projectedNote: 'La columna proyectada existe como contexto. No entra en el orden.',
  },
  finance: {
    title: 'Finanzas',
    subtitle: 'Detalle completo de efectivo, base distribuible y liquidaciones.',
    cashReceived: 'Efectivo recibido',
    approvedBase: 'Base aprobada',
    projectedBase: 'Base proyectada',
    paidOut: 'Pagado',
    owed: 'Por pagar',
    house: 'Casa',
    pendingApprovals: 'Liquidaciones por aprobar',
    ledger: 'Movimientos',
    review: 'Revisar liquidación',
  },
  settle: {
    title: 'Aprobación de liquidación',
    subtitle: 'Vista previa. En M1 no existe ninguna ruta de escritura.',
    approve: 'Aprobar liquidación',
    blockedInM1: 'La aprobación se habilita en M2, con RLS y registro de auditoría en Postgres.',
    checks: 'Verificaciones',
    checkWeights: 'Pesos de producción completos',
    checkMilestones: 'Hitos pendientes',
    checkBase: 'Base distribuible confirmada',
    alreadyApproved: 'Esta oportunidad ya tiene una liquidación aprobada',
  },
  admin: {
    title: 'Admin',
    subtitle: 'Vista de fundador sobre proyectos, cartera y aprobaciones.',
    portfolio: 'Cartera',
    attention: 'Requiere atención',
    nothingPending: 'Nada pendiente',
  },
  opportunity: {
    statusLabels: {
      draft: 'Borrador',
      assigned: 'Asignada',
      in_delivery: 'En producción',
      delivered: 'Entregada',
      settled_approved: 'Liquidada',
      paid: 'Pagada',
      cancelled: 'Cancelada',
    },
  },
} as const;
