#!/usr/bin/env node
/**
 * Generates supabase/seed.sql from the exact same fixture JSON that backs the
 * M1 synthetic repositories, so the development Supabase project starts from
 * data that is already reviewed and covered by tests/data/fixtures.test.ts.
 *
 * Run: node scripts/generate-seed.mjs > supabase/seed.sql
 * Re-run whenever a fixture file under src/data/fixtures/** changes.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const fixturesDir = path.join(root, 'src', 'data', 'fixtures');

function readFixture(relativePath) {
  const raw = readFileSync(path.join(fixturesDir, relativePath), 'utf8');
  return JSON.parse(raw).records;
}

function sqlString(value) {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlJson(value) {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function sqlArray(values) {
  if (values.length === 0) return "'{}'::uuid[]";
  return `array[${values.map((v) => sqlString(v)).join(', ')}]::uuid[]`;
}

function insert(table, columns, rows, conflictColumn = 'id') {
  if (rows.length === 0) return `-- ${table}: nothing to seed\n`;
  const lines = rows.map((row) => `  (${columns.map((c) => row[c]).join(', ')})`);
  return `insert into public.${table} (${columns.join(', ')}) values\n${lines.join(',\n')}\non conflict (${conflictColumn}) do nothing;\n`;
}

const PROJECT_SLUGS = ['sety-2026', 'ai-ops-retainer', 'even-internal-2026'];

const out = [];
out.push('-- Generated by scripts/generate-seed.mjs. Do not hand-edit; regenerate instead.');
out.push('-- Mirrors src/data/fixtures/** exactly, so this dev-project seed matches the');
out.push('-- fixtures already validated by tests/data/fixtures.test.ts.');
out.push(
  '--\n-- Wrapped in one transaction: several deferred constraints (settlement\n' +
    '-- line sums, reversal exactness, payout reconciliation) are only checked at\n' +
    '-- COMMIT, and this seed inserts a cash event in one statement and its\n' +
    '-- settlement_line_payouts allocation in a later one. Run statement-by-\n' +
    '-- statement under autocommit, the first statement would commit — and fail\n' +
    "-- its deferred check — before the second statement ever runs.\n\nbegin;\n",
);

// organizations
const organizations = readFixture('organizations.json');
out.push(
  insert(
    'organizations',
    ['id', 'slug', 'name'],
    organizations.map((o) => ({ id: sqlString(o.id), slug: sqlString(o.slug), name: sqlString(o.name) })),
  ),
);

// members (org_id defaults to the first org, matching every member fixture record)
const members = readFixture('members.json');
out.push(
  insert(
    'members',
    ['id', 'org_id', 'slug', 'display_name', 'initials', 'role'],
    members.map((m) => ({
      id: sqlString(m.id),
      org_id: sqlString(m.orgId),
      slug: sqlString(m.slug),
      display_name: sqlString(m.displayName),
      initials: sqlString(m.initials),
      role: sqlString(m.role),
    })),
  ),
);

// memberships — every fixture member is invited but not yet activated. A
// founder redeems real access by inviting a real email via member_invites;
// this repo has no real email addresses to seed (see docs/PRODUCT-BRIEF.md:
// identity is a UUID and email, never invented here).
out.push(
  insert(
    'memberships',
    ['id', 'org_id', 'member_id', 'status'],
    members.map((m) => ({
      id: `gen_random_uuid()`,
      org_id: sqlString(m.orgId),
      member_id: sqlString(m.id),
      status: sqlString('invited'),
    })),
  ),
);

// member_profiles
const memberProfiles = readFixture('member-profiles.json');
out.push(
  insert(
    'member_profiles',
    ['member_id', 'bio', 'availability', 'next_capability', 'joined_at'],
    memberProfiles.map((p) => ({
      member_id: sqlString(p.memberId),
      bio: sqlString(p.bio),
      availability: sqlString(p.availability),
      next_capability: sqlString(p.nextCapability),
      joined_at: sqlString(p.joinedAt),
    })),
    'member_id',
  ),
);

// skills
const skills = readFixture('skills.json');
out.push(
  insert(
    'skills',
    ['id', 'key', 'name', 'family'],
    skills.map((s) => ({ id: sqlString(s.id), key: sqlString(s.key), name: sqlString(s.name), family: sqlString(s.family) })),
  ),
);

// member_skills
const memberSkills = readFixture('member-skills.json');
out.push(
  insert(
    'member_skills',
    ['id', 'member_id', 'skill_id', 'level', 'verification'],
    memberSkills.map((ms) => ({
      id: sqlString(ms.id),
      member_id: sqlString(ms.memberId),
      skill_id: sqlString(ms.skillId),
      level: sqlString(ms.level),
      verification: sqlString(ms.verification),
    })),
  ),
);

// portfolio_items
const portfolioItems = readFixture('portfolio-items.json');
out.push(
  insert(
    'portfolio_items',
    ['id', 'member_id', 'title', 'role_label', 'url', 'kind', 'verification', 'completed_at'],
    portfolioItems.map((p) => ({
      id: sqlString(p.id),
      member_id: sqlString(p.memberId),
      title: sqlString(p.title),
      role_label: sqlString(p.roleLabel),
      url: sqlString(p.url),
      kind: sqlString(p.kind),
      verification: sqlString(p.verification),
      completed_at: sqlString(p.completedAt),
    })),
  ),
);

// Per-project bundles
const allServiceVersions = [];
const allMilestoneTemplates = [];
const allAllocationRuleVersions = [];
const allAllocationShares = [];
const allOpportunities = [];
const allAssignments = [];
const allOpportunityMilestones = [];
const allEvidenceLinks = [];
const allCashEvents = [];
const allSettlements = [];
const allSettlementLines = [];
const allSettlementLinePayouts = [];
const projectRows = [];

for (const slug of PROJECT_SLUGS) {
  const dir = `projects/${slug}`;
  const [project] = readFixture(`${dir}/project.json`);
  projectRows.push(project);
  allServiceVersions.push(...readFixture(`${dir}/service-versions.json`));
  allMilestoneTemplates.push(...readFixture(`${dir}/milestone-templates.json`));
  allAllocationRuleVersions.push(...readFixture(`${dir}/allocation-rule-versions.json`));
  allOpportunities.push(...readFixture(`${dir}/opportunities.json`));
  allAssignments.push(...readFixture(`${dir}/assignments.json`));
  allOpportunityMilestones.push(...readFixture(`${dir}/opportunity-milestones.json`));
  allEvidenceLinks.push(...readFixture(`${dir}/evidence-links.json`));
  allCashEvents.push(...readFixture(`${dir}/cash-events.json`));
  allSettlements.push(...readFixture(`${dir}/settlements.json`));
  allSettlementLines.push(...readFixture(`${dir}/settlement-lines.json`));
  allSettlementLinePayouts.push(...readFixture(`${dir}/settlement-line-payouts.json`));
}

// projects — inserted without active_allocation_rule_version_id first, then
// backfilled, since that column's FK target is seeded after this insert.
out.push(
  insert(
    'projects',
    ['id', 'org_id', 'slug', 'name', 'sponsor_name', 'status', 'currency'],
    projectRows.map((p) => ({
      id: sqlString(p.id),
      org_id: sqlString(organizations[0].id),
      slug: sqlString(p.slug),
      name: sqlString(p.name),
      sponsor_name: sqlString(p.sponsorName),
      status: sqlString(p.status),
      currency: sqlString(p.currency),
    })),
  ),
);

out.push(
  insert(
    'service_versions',
    ['id', 'project_id', 'key', 'name', 'version', 'deliverables_summary'],
    allServiceVersions.map((s) => ({
      id: sqlString(s.id),
      project_id: sqlString(s.projectId),
      key: sqlString(s.key),
      name: sqlString(s.name),
      version: s.version,
      deliverables_summary: sqlString(s.deliverablesSummary),
    })),
  ),
);

out.push(
  insert(
    'milestone_templates',
    ['id', 'service_version_id', 'position', 'name', 'description'],
    allMilestoneTemplates.map((m) => ({
      id: sqlString(m.id),
      service_version_id: sqlString(m.serviceVersionId),
      position: m.position,
      name: sqlString(m.name),
      description: sqlString(m.description),
    })),
  ),
);

out.push(
  insert(
    'allocation_rule_versions',
    ['id', 'project_id', 'version', 'effective_from', 'currency', 'base_policy'],
    allAllocationRuleVersions.map((r) => ({
      id: sqlString(r.id),
      project_id: sqlString(r.projectId),
      version: r.version,
      effective_from: sqlString(r.effectiveFrom),
      currency: sqlString(r.currency),
      base_policy: sqlJson(r.basePolicy),
    })),
  ),
);

for (const r of allAllocationRuleVersions) {
  for (const share of r.shares) {
    allAllocationShares.push({ ruleVersionId: r.id, ...share });
  }
}
out.push(
  insert(
    'allocation_shares',
    ['id', 'rule_version_id', 'key', 'recipient_behavior', 'label', 'weight_bp', 'recipient_org_id'],
    allAllocationShares.map((s) => ({
      id: 'gen_random_uuid()',
      rule_version_id: sqlString(s.ruleVersionId),
      key: sqlString(s.key),
      recipient_behavior: sqlString(s.recipientBehavior),
      label: sqlString(s.label),
      weight_bp: s.weightBp,
      recipient_org_id: sqlString(s.recipientOrgId),
    })),
  ),
);

out.push(
  `\nupdate public.projects p set active_allocation_rule_version_id = arv.id\nfrom public.allocation_rule_versions arv\nwhere arv.project_id = p.id and p.id in (${projectRows
    .filter((p) => p.activeAllocationRuleVersionId !== null)
    .map((p) => sqlString(p.id))
    .join(', ')})\nand arv.id in (${allAllocationRuleVersions.map((r) => sqlString(r.id)).join(', ')});\n`,
);

out.push(
  insert(
    'opportunities',
    ['id', 'project_id', 'service_version_id', 'allocation_rule_version_id', 'code', 'beneficiary_name', 'beneficiary_location', 'status', 'opened_at'],
    allOpportunities.map((o) => ({
      id: sqlString(o.id),
      project_id: sqlString(o.projectId),
      service_version_id: sqlString(o.serviceVersionId),
      allocation_rule_version_id: sqlString(o.allocationRuleVersionId),
      code: sqlString(o.code),
      beneficiary_name: sqlString(o.beneficiaryName),
      beneficiary_location: sqlString(o.beneficiaryLocation),
      status: sqlString(o.status),
      opened_at: sqlString(o.openedAt),
    })),
  ),
);

out.push(
  insert(
    'assignments',
    ['id', 'opportunity_id', 'member_id', 'role_key', 'role_label', 'weight_bp', 'status'],
    allAssignments.map((a) => ({
      id: sqlString(a.id),
      opportunity_id: sqlString(a.opportunityId),
      member_id: sqlString(a.memberId),
      role_key: sqlString(a.roleKey),
      role_label: sqlString(a.roleLabel),
      weight_bp: a.weightBp,
      status: sqlString(a.status),
    })),
  ),
);

out.push(
  insert(
    'opportunity_milestones',
    ['id', 'opportunity_id', 'template_id', 'position', 'name', 'status', 'due_at', 'completed_at', 'assigned_member_id'],
    allOpportunityMilestones.map((m) => ({
      id: sqlString(m.id),
      opportunity_id: sqlString(m.opportunityId),
      template_id: sqlString(m.templateId),
      position: m.position,
      name: sqlString(m.name),
      status: sqlString(m.status),
      due_at: sqlString(m.dueAt),
      completed_at: sqlString(m.completedAt),
      assigned_member_id: sqlString(m.assignedMemberId),
    })),
  ),
);

out.push(
  insert(
    'evidence_links',
    ['id', 'opportunity_milestone_id', 'label', 'url', 'kind', 'submitted_by_member_id', 'submitted_at'],
    allEvidenceLinks.map((e) => ({
      id: sqlString(e.id),
      opportunity_milestone_id: sqlString(e.opportunityMilestoneId),
      label: sqlString(e.label),
      url: sqlString(e.url),
      kind: sqlString(e.kind),
      submitted_by_member_id: sqlString(e.submittedByMemberId),
      submitted_at: sqlString(e.submittedAt),
    })),
  ),
);

out.push(
  insert(
    'cash_events',
    ['id', 'opportunity_id', 'type', 'label', 'amount_centavos', 'currency', 'occurred_at'],
    allCashEvents.map((c) => ({
      id: sqlString(c.id),
      opportunity_id: sqlString(c.opportunityId),
      type: sqlString(c.type),
      label: sqlString(c.label),
      amount_centavos: c.amountCentavos,
      currency: sqlString(c.currency),
      occurred_at: sqlString(c.occurredAt),
    })),
  ),
);

out.push(
  insert(
    'settlements',
    ['id', 'opportunity_id', 'allocation_rule_version_id', 'status', 'kind', 'corrects_settlement_id', 'base_centavos', 'currency', 'approved_at', 'approved_by_member_id'],
    allSettlements.map((s) => ({
      id: sqlString(s.id),
      opportunity_id: sqlString(s.opportunityId),
      allocation_rule_version_id: sqlString(s.allocationRuleVersionId),
      status: sqlString(s.status),
      kind: sqlString(s.kind),
      corrects_settlement_id: sqlString(s.correctsSettlementId),
      base_centavos: s.baseCentavos,
      currency: sqlString(s.currency),
      approved_at: sqlString(s.approvedAt),
      approved_by_member_id: sqlString(s.approvedByMemberId),
    })),
  ),
);

out.push(
  insert(
    'settlement_lines',
    ['id', 'settlement_id', 'share_key', 'recipient_behavior', 'recipient_label', 'member_id', 'role_label', 'weight_bp', 'amount_centavos', 'currency', 'sequence'],
    allSettlementLines.map((l) => ({
      id: sqlString(l.id),
      settlement_id: sqlString(l.settlementId),
      share_key: sqlString(l.shareKey),
      recipient_behavior: sqlString(l.recipientBehavior),
      recipient_label: sqlString(l.recipientLabel),
      member_id: sqlString(l.memberId),
      role_label: sqlString(l.roleLabel),
      weight_bp: l.weightBp,
      amount_centavos: l.amountCentavos,
      currency: sqlString(l.currency),
      sequence: l.sequence,
    })),
  ),
);

// A founder identity to attribute seeded payout allocations to. Matches the
// same convention already used below for source_documents/intake_runs.
const seedFounderId = members.find((m) => m.role === 'founder').id;

out.push(
  insert(
    'settlement_line_payouts',
    ['id', 'settlement_line_id', 'payout_cash_event_id', 'amount_centavos', 'currency', 'created_at', 'created_by_member_id', 'idempotency_key'],
    allSettlementLinePayouts.map((p) => ({
      id: sqlString(p.id),
      settlement_line_id: sqlString(p.settlementLineId),
      payout_cash_event_id: sqlString(p.payoutCashEventId),
      amount_centavos: p.amountCentavos,
      currency: sqlString(p.currency),
      created_at: sqlString(p.createdAt),
      created_by_member_id: sqlString(p.createdByMemberId ?? seedFounderId),
      idempotency_key: sqlString(p.idempotencyKey),
    })),
  ),
);

// stat_events
const statEvents = readFixture('stat-events.json');
out.push(
  insert(
    'stat_events',
    ['id', 'member_id', 'opportunity_id', 'metric_key', 'quantity', 'source_kind', 'source_id', 'reverses_stat_event_id', 'occurred_at'],
    statEvents.map((e) => ({
      id: sqlString(e.id),
      member_id: sqlString(e.memberId),
      opportunity_id: sqlString(e.opportunityId),
      metric_key: sqlString(e.metricKey),
      quantity: e.quantity,
      source_kind: sqlString(e.sourceKind),
      source_id: sqlString(e.sourceId),
      reverses_stat_event_id: sqlString(e.reversesStatEventId),
      occurred_at: sqlString(e.occurredAt),
    })),
  ),
);

// source_documents + ai_contract_drafts (the document-intake fixtures)
const sourceDocuments = readFixture('source-documents.json');
out.push(
  insert(
    'source_documents',
    ['id', 'org_id', 'uploaded_by_member_id', 'filename', 'kind', 'uploaded_at'],
    sourceDocuments.map((d) => ({
      id: sqlString(d.id),
      org_id: sqlString(d.orgId),
      // Founder-uploaded in the fixture story; seed it against the first
      // founder in members.json rather than inventing a new identity.
      uploaded_by_member_id: sqlString(members.find((m) => m.role === 'founder').id),
      filename: sqlString(d.filename),
      kind: sqlString(d.kind),
      uploaded_at: sqlString(d.uploadedAt),
    })),
  ),
);

const aiContractDrafts = readFixture('ai-contract-drafts.json');
out.push(
  `-- ai_contract_drafts needs an intake_runs parent; seed one synthetic\n` +
    `-- 'ready' run per draft so foreign keys resolve, matching how run_intake()\n` +
    `-- would have created it.\n`,
);
for (const d of aiContractDrafts) {
  out.push(
    `with seeded_run as (\n` +
      `  insert into public.intake_runs (org_id, requested_by_member_id, status, source_document_id, idempotency_key, synthetic, completed_at)\n` +
      `  values (${sqlString(d.orgId)}, ${sqlString(members.find((m) => m.role === 'founder').id)}, 'ready', ${sqlString(d.sourceDocumentId)}, 'seed-${d.id}', true, now())\n` +
      `  returning id\n` +
      `)\n` +
      `insert into public.ai_contract_drafts (\n` +
      `  id, intake_run_id, source_document_id, org_id, matched_project_id, matched_service_version_ids,\n` +
      `  matched_allocation_rule_version_id, sponsor_name, program_name, currency, example_distributable_base,\n` +
      `  example_distributable_base_note, review_issues, suggested_assignments\n` +
      `)\n` +
      `select\n` +
      `  ${sqlString(d.id)}, seeded_run.id, ${sqlString(d.sourceDocumentId)}, ${sqlString(d.orgId)}, ${sqlString(d.matchedProjectId)},\n` +
      `  ${sqlArray(d.matchedServiceVersionIds)}, ${sqlString(d.matchedAllocationRuleVersionId)}, ${sqlJson(d.sponsorName)},\n` +
      `  ${sqlJson(d.programName)}, ${sqlString(d.currency)}, ${sqlJson(d.exampleDistributableBase)}, ${sqlString(d.exampleDistributableBaseNote)},\n` +
      `  ${sqlJson(d.reviewIssues)}, ${sqlJson(d.suggestedAssignments)}\n` +
      `from seeded_run\n` +
      `on conflict (id) do nothing;\n\n` +
      `update public.intake_runs set draft_id = ${sqlString(d.id)}\n` +
      `where source_document_id = ${sqlString(d.sourceDocumentId)} and draft_id is null and status = 'ready';\n`,
  );
}

out.push('\ncommit;\n');

process.stdout.write(out.join('\n') + '\n');
